runtime: python311

automatic_scaling:
  max_instances: 10
  min_instances: 0

handlers:
  # Serve static assets - use simpler pattern that works
  - url: /(.+\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|map))
    static_files: dist/\1
    upload: dist/.+\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|map)
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=86400'

  # Serve index.html for the root
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Access-Control-Allow-Origin: '*'

  # Fallback to index.html for client-side routing - MUST be last
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Access-Control-Allow-Origin: '*'
