name: personal-website
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          # cache: npm
      - name: Install Angular CLI
        run: sudo npm i @angular/cli --force
      - name: Install Angular Build
        run: sudo npm i @angular-devkit/build-angular --force
      - name: Build Frontend
        run: sudo npm run build --force
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.5.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
