name: personal-website
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Frontend
        run: npm run build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}
          promote: false
      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
